# name: Build APK Fast

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-java@v4
#         with:
#           distribution: 'zulu'
#           java-version: '17'

#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#           flutter-version: '3.19.0'

#       - name: Get Dependencies
#         run: flutter pub get

#       - name: Build APK
#         run: flutter build apk --release --no-tree-shake-icons

#       - name: Upload APK
#         uses: actions/upload-artifact@v4
#         with:
#           name: fitness-emulator-release
#           path: build/app/outputs/flutter-apk/app-release.apk
